# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.twig_extension:
        class: Plopcom\InscriptionsBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    app.form.inscription:
            class: Plopcom\InscriptionsBundle\Form\InscriptionType
            arguments: ['@security.token_storage']
            tags:
                - { name: form.type }
    app.file_type_extension:
            class: Plopcom\InscriptionsBundle\Form\Extension\FileTypeExtension
            tags:
                - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }