<?php

namespace Plopcom\InscriptionsBundle\Repository;

/**
 * AthleteOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AthleteOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
