<?php

namespace Plopcom\InscriptionsBundle\Repository;

use Plopcom\InscriptionsBundle\Entity\Configuration;

/**
 * ConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getInstance(){
        $r = $this->findOneBy(array());
        if (!$r)
            return new Configuration();
        return $r;
    }
}
