<?php

namespace Plopcom\InscriptionsBundle\Repository;

/**
 * InscriptionOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
