<?php

namespace Plopcom\InscriptionsBundle\Repository;

/**
 * RaceOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
